"""世界运行引擎。

状态推演保持纯内存、纯函数语义；已提交的 WorldState / WorldEvent 可通过
SQLiteWorldStore 持久化。后续迁移 PostgreSQL 时，Turn Pipeline 无需改动。
"""

from .patch import apply_patch, PatchError
from .event import commit_event, replay_events
from .rules import RuleEngine, RuleCheckResult
from .action_parser import ActionParser, ParseError
from .transition import TransitionProposer
from .patch_validator import (
    PatchCheckResult,
    validate_action_patch,
    validate_patch,
    validate_tool_patch,
)
from .narrative import NarrativeGenerator
from .narrative_consistency import check_narrative, NarrativeCheckResult
from .character_agent import CharacterAgent, candidate_to_action
from .agent_scheduler import (
    CharacterScheduler,
    AgentScheduleResult,
    NPCReaction,
    merge_patches,
)
from .turn import TurnPipeline, TurnResult
from .persistence import (
    MemoryRecord,
    PersistenceError,
    SessionMetadata,
    SessionNotFound,
    SQLiteWorldStore,
    TurnRecord,
    VersionConflict,
)
from .agent_tools import (
    CORE_TOOL_PERMISSIONS,
    DestroyItemArguments,
    GiveItemArguments,
    MoveToArguments,
    ObserveArguments,
    PickUpArguments,
    PresentationEvent,
    ProposeAllianceArguments,
    ShareInformationArguments,
    TalkToArguments,
    ToolCall,
    ToolCandidate,
    ToolContext,
    ToolDefinition,
    ToolExecutionError,
    ToolFailure,
    ToolFailureCode,
    ToolRegistry,
    ToolResult,
    create_core_tool_registry,
)
from .agent_trace import (
    AgentTrace,
    AgentTraceRecorder,
    AgentTraceSpan,
    TraceSpanStatus,
    TraceStage,
)
from .llm_telemetry import (
    LLMCallUsage,
    LLMUsageCollector,
    LLMUsageSummary,
    call_openai_compatible,
    capture_llm_usage,
    chat_generation_options,
)
from .agent_runtime import (
    AgentExecution,
    AgentExecutionOutcome,
    AgentExecutionState,
    AgentExecutionStateMachine,
    AgentExecutionStatus,
)
from .game_observation import (
    AvailableTool,
    GameObservation,
    ObservedBelief,
    ObservedGoal,
    ObservedMemory,
    ObservedPlan,
    PlannerFeedback,
    VisibleCharacter,
    VisibleItem,
    VisibleLocation,
    authoritative_state_hash,
    build_game_observation,
)
from .planner_decision import PlannerDecision, PlannerIntent
from .planner_policy import (
    PlannerPolicy,
    PlannerPolicyConfig,
    PlannerPolicyError,
    PlannerPolicyKind,
    PlannerPolicyRouter,
    PlannerPolicySceneSelector,
    PromptedLLMPolicy,
    ReActPolicy,
    ScriptedPolicy,
    coerce_planner_decision,
    tool_definitions_from_observation,
)
from .embeddings import (
    CachedMemoryEmbedder,
    EmbeddingError,
    MemoryEmbedder,
    OpenAICompatibleEmbedder,
    memory_embedder_from_env,
)
from .memory_retrieval_eval import (
    QueryRetrievalResult,
    RetrievalBenchmark,
    RetrievalDocument,
    RetrievalQuery,
    RetrievalReport,
    evaluate_retrieval,
    evaluate_store,
    load_retrieval_benchmark,
    seed_retrieval_benchmark,
)
from .postgres_persistence import PostgresWorldStore
from .qdrant_memory import (
    HybridRetrievalWeights,
    QdrantBackedWorldStore,
    QdrantMemoryHit,
    QdrantMemoryIndex,
)
from .store_factory import create_world_store
from .storage import WorldStore
from .memory_projection import (
    event_memory_characters,
    event_memory_content,
    rebuild_session_memories,
    record_event_memory,
)
from .reflection_memory import (
    ReflectionCandidate,
    ReflectionGenerator,
    ReflectionReport,
    ReflectionSemanticJudge,
    ReflectionSemanticScore,
    filter_compatible_memories,
    memory_conflicts_with_state,
    reflect_character_memories,
    reflection_source_id,
)
from .trajectory_eval import (
    TrajectoryReport,
    TrajectoryViolation,
    evaluate_trajectory,
)
from .llm_trajectory_eval import (
    LLMTrajectoryEvaluator,
    LLMTrajectoryReport,
    TrajectoryQualityIssue,
    TrajectoryQualityScore,
)
from .world_packages import (
    WorldPackageConflict,
    WorldPackageError,
    WorldPackageNotFound,
    WorldPackageRecord,
    WorldPackageStore,
    WorldPackageValidationError,
    validate_world_package_payload,
)
from .scene_controller import (
    SceneConfig,
    SceneController,
    SceneEnding,
    SceneMode,
    SceneRun,
    SceneStatus,
    SceneStep,
    SceneSummary,
    ScriptBeat,
)
from .presentation_stream import (
    COMMANDS_PER_WORLD_VERSION,
    PresentationCommand,
    build_turn_presentation_events,
    cursor_after_world_version,
    project_presentation_commands,
)

__all__ = [
    "apply_patch",
    "PatchError",
    "commit_event",
    "replay_events",
    "RuleEngine",
    "RuleCheckResult",
    "ActionParser",
    "ParseError",
    "TransitionProposer",
    "validate_patch",
    "validate_action_patch",
    "validate_tool_patch",
    "PatchCheckResult",
    "NarrativeGenerator",
    "check_narrative",
    "NarrativeCheckResult",
    "CharacterAgent",
    "candidate_to_action",
    "CharacterScheduler",
    "AgentScheduleResult",
    "NPCReaction",
    "merge_patches",
    "TurnPipeline",
    "TurnResult",
    "MemoryRecord",
    "PersistenceError",
    "SessionMetadata",
    "SessionNotFound",
    "SQLiteWorldStore",
    "TurnRecord",
    "VersionConflict",
    "CORE_TOOL_PERMISSIONS",
    "DestroyItemArguments",
    "GiveItemArguments",
    "MoveToArguments",
    "ObserveArguments",
    "PickUpArguments",
    "PresentationEvent",
    "ProposeAllianceArguments",
    "ShareInformationArguments",
    "TalkToArguments",
    "ToolCall",
    "ToolCandidate",
    "ToolContext",
    "ToolDefinition",
    "ToolExecutionError",
    "ToolFailure",
    "ToolFailureCode",
    "ToolRegistry",
    "ToolResult",
    "create_core_tool_registry",
    "AgentTrace",
    "AgentTraceRecorder",
    "AgentTraceSpan",
    "TraceSpanStatus",
    "TraceStage",
    "LLMCallUsage",
    "LLMUsageCollector",
    "LLMUsageSummary",
    "call_openai_compatible",
    "capture_llm_usage",
    "chat_generation_options",
    "AgentExecution",
    "AgentExecutionOutcome",
    "AgentExecutionState",
    "AgentExecutionStateMachine",
    "AgentExecutionStatus",
    "AvailableTool",
    "GameObservation",
    "ObservedBelief",
    "ObservedGoal",
    "ObservedMemory",
    "ObservedPlan",
    "PlannerFeedback",
    "VisibleCharacter",
    "VisibleItem",
    "VisibleLocation",
    "authoritative_state_hash",
    "build_game_observation",
    "PlannerDecision",
    "PlannerIntent",
    "PlannerPolicy",
    "PlannerPolicyConfig",
    "PlannerPolicyError",
    "PlannerPolicyKind",
    "PlannerPolicyRouter",
    "PlannerPolicySceneSelector",
    "PromptedLLMPolicy",
    "ReActPolicy",
    "ScriptedPolicy",
    "coerce_planner_decision",
    "tool_definitions_from_observation",
    "EmbeddingError",
    "CachedMemoryEmbedder",
    "MemoryEmbedder",
    "OpenAICompatibleEmbedder",
    "memory_embedder_from_env",
    "QueryRetrievalResult",
    "RetrievalBenchmark",
    "RetrievalDocument",
    "RetrievalQuery",
    "RetrievalReport",
    "evaluate_retrieval",
    "evaluate_store",
    "load_retrieval_benchmark",
    "seed_retrieval_benchmark",
    "PostgresWorldStore",
    "HybridRetrievalWeights",
    "QdrantBackedWorldStore",
    "QdrantMemoryHit",
    "QdrantMemoryIndex",
    "create_world_store",
    "WorldStore",
    "event_memory_characters",
    "event_memory_content",
    "rebuild_session_memories",
    "record_event_memory",
    "ReflectionCandidate",
    "ReflectionGenerator",
    "ReflectionReport",
    "ReflectionSemanticJudge",
    "ReflectionSemanticScore",
    "filter_compatible_memories",
    "memory_conflicts_with_state",
    "reflect_character_memories",
    "reflection_source_id",
    "TrajectoryReport",
    "TrajectoryViolation",
    "evaluate_trajectory",
    "LLMTrajectoryEvaluator",
    "LLMTrajectoryReport",
    "TrajectoryQualityIssue",
    "TrajectoryQualityScore",
    "WorldPackageConflict",
    "WorldPackageError",
    "WorldPackageNotFound",
    "WorldPackageRecord",
    "WorldPackageStore",
    "WorldPackageValidationError",
    "validate_world_package_payload",
    "SceneConfig",
    "SceneController",
    "SceneEnding",
    "SceneMode",
    "SceneRun",
    "SceneStatus",
    "SceneStep",
    "SceneSummary",
    "ScriptBeat",
    "COMMANDS_PER_WORLD_VERSION",
    "PresentationCommand",
    "build_turn_presentation_events",
    "cursor_after_world_version",
    "project_presentation_commands",
]
